output_schema:
  - field: bee_species
    type: list
    description: "Bee species studied, give the full species name with subspecies when available. Only give the common name when the latin name isn't provided."
    csv_include_field: false
  
  - field: pesticides_data
    type: complex
    description: "Structured pesticide information including doses, exposure times, etc."
    csv_include_field: false
    paths:
      - ["QUESTIONS", "bee_and_pesticides", "pesticides", "answer"]
      - ["QUESTIONS", "bee_and_pesticides", "pesticides", "reason"]
    subfields:
      - field: name
        type: string
        description: "Name of the pesticide"
      - field: exposure_methods
        type: complex_array
        description: "Methods of exposure and their corresponding details"
        paths:
          - ["QUESTIONS", "bee_and_pesticides", "pesticides", "answer"]
          - ["QUESTIONS", "bee_and_pesticides", "pesticides", "reason"]
        subfields:
          - field: method
            type: string
            description: "Method of exposure (e.g., oral, contact, etc.)"
          - field: doses
            type: list
            number: true
            description: "Dosage levels used for this pesticide with this exposure method"
          - field: dose_units
            type: string
            description: "Units for the dosage (e.g., ng/bee, mg/bee)"
          - field: exposure_duration
            type: list
            number: true
            description: "Exposure duration(s) for this pesticide with this exposure method"
          - field: exposure_units
            type: string
            description: "Units for the exposure duration (e.g., hours, days)"
          - field: mixture_details
            type: list
            description: "Whether the pesticide was used alone (single exposure) or in a mixture (provide co-exposure pesticides or other stressors if applicable)"
  
  - field: additional_stressors
    type: list
    description: "List of additional stressors used in the study"
    exclude_fields: ["pesticides_data.name"]
    csv_include_field: false

output_formats:
  - csv
  - json

data_mappings:
  bee_species:
    paths:
      - ["QUESTIONS", "bee_and_pesticides", "bee_species", "answer"]
      - ["QUESTIONS", "bee_and_pesticides", "bee_species", "reason"]
    category: "BEES"
    question: "What bee species were used? Give the full species name(s) when possible."
  
  pesticides_data:
    category: "PESTICIDES"
    question: "Extract structured information about all pesticides used, including their doses and units, exposure duration and units, and whether the pesticide was used alone or in a mixture."
  
  additional_stressors:
    paths:
      - ["QUESTIONS", "bee_and_pesticides", "additional_stressors", "answer"]
      - ["QUESTIONS", "bee_and_pesticides", "additional_stressors", "reason"]
    category: "ADDITIONAL STRESSORS"
    question: "What additional stressors were used?"
    
  